const PDFDocument = require('pdfkit');


// =====================================================
// GENERATE CONVERSATION PDF
// =====================================================

const generateConversationPdf = (
    conversation
) => {

    return new Promise(
        (resolve, reject) => {

            try {

                const doc =
                    new PDFDocument({
                        margin: 50
                    });


                const chunks = [];


                // ==========================================
                // COLLECT PDF DATA
                // ==========================================

                doc.on(
                    'data',
                    chunk => {
                        chunks.push(chunk);
                    }
                );


                doc.on(
                    'end',
                    () => {

                        const pdfBuffer =
                            Buffer.concat(
                                chunks
                            );

                        resolve(
                            pdfBuffer
                        );

                    }
                );


                doc.on(
                    'error',
                    error => {
                        reject(error);
                    }
                );


                // ==========================================
                // TITLE
                // ==========================================

                doc
                    .fontSize(20)
                    .font('Helvetica-Bold')
                    .text(
                        'AI Chat Conversation',
                        {
                            align: 'center'
                        }
                    );


                doc.moveDown();


                // ==========================================
                // CONVERSATION TITLE
                // ==========================================

                doc
                    .fontSize(13)
                    .font('Helvetica-Bold')
                    .text(
                        conversation.title ||
                        'Conversation'
                    );


                doc.moveDown();


                // ==========================================
                // GENERATED DATE
                // ==========================================

                doc
                    .fontSize(9)
                    .font('Helvetica')
                    .text(
                        `Generated: ${new Date().toLocaleString()}`
                    );


                doc.moveDown();
                doc.moveDown();


                // ==========================================
                // MESSAGES
                // ==========================================

                for (
                    const message
                    of conversation.messages
                ) {

                    const author =
                        message.role === 'user'
                            ? 'You'
                            : 'AI Assistant';


                    // --------------------------------------
                    // AUTHOR
                    // --------------------------------------

                    doc
                        .fontSize(11)
                        .font('Helvetica-Bold')
                        .text(author);


                    doc.moveDown(0.3);


                    // --------------------------------------
                    // MESSAGE
                    // --------------------------------------

                    doc
                        .fontSize(10)
                        .font('Helvetica')
                        .text(
                            message.content ||
                            ''
                        );


                    doc.moveDown();


                    // --------------------------------------
                    // SEPARATOR
                    // --------------------------------------

                    doc
                        .moveTo(
                            50,
                            doc.y
                        )
                        .lineTo(
                            545,
                            doc.y
                        )
                        .stroke();


                    doc.moveDown();

                }


                // ==========================================
                // FOOTER
                // ==========================================

                doc
                    .fontSize(8)
                    .font('Helvetica')
                    .text(
                        'Generated by AI Chat',
                        50,
                        750,
                        {
                            align: 'center'
                        }
                    );


                // ==========================================
                // FINISH
                // ==========================================

                doc.end();


            } catch (error) {

                reject(error);

            }

        }
    );

};


module.exports = {

    generateConversationPdf

};